[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

build_flags = 
    -DCONFIG_WIFI_SSID=\"Hkgodhani1\"
    -DCONFIG_WIFI_PASSWORD=\"Hkgodhani\"
    -DCONFIG_STRATUM_POOL=\"stratum+tcp://eu3.solopool.org:8002\"
    -DCONFIG_WORKER_NAME=\"bc1q8p6fh9mflm5057d2sm3drl8fuzykyy3m0ja6hv\"
    -DCONFIG_FB_WALLET=\"bc1q8p6fh9mflm5057d2sm3drl8fuzykyy3m0ja6hv\"
    -DPROFILE_ENABLED

lib_deps = 
